<a href="https://colab.research.google.com/github/hisjeans/data-analysis-ml/blob/main/Numpy%E1%84%80%E1%85%AA%E1%84%8C%E1%85%A6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

1) 아래 최종 결과를 참고하여 A, B, C 문항의 코드를 작성하라

> [Numpy Array Example]  
> [9 5 0 3 3 3 1 6 9 1 3] -> 0번째 원소  
> [8 2 3 8 3 8 2 3 9 1 8] -> 1번째 원소  
> [0 3 4 2 5 4 5 4 5 2 4] -> 2번째 원소  
> [8 0 3 6 8 0 2 9 3 4 4] -> 3번째 원소  
> [3 0 4 1 6 2 8 3 7 2 5] -> 4번째 원소  
>  
> [위 예시에 대한 정답]  
> [9 5 0 3 3 3 1 6 9 1 3] -> 0번째 원소  
> [8 2 3 8 3 8 2 3 9 1 8] -> 1번째 원소  
> [8 0 3 6 8 0 2 9 3 4 4] -> 3번째 원소  
> [0 3 4 2 5 4 5 4 5 2 4] -> 2번째 원소  
> [3 0 4 1 6 2 8 3 7 2 5] -> 4번째 원소  

A. (1, 10)의 배열을 랜덤적으로 5개 생성하라.

In [2]:
A=[np.random.randint(1,11,size=11) for _ in range(5)]

B. 생성된 5개의 배열을 합쳐 2차원 배열을 생성하라.

In [3]:
B=np.vstack(A)
B

array([[ 2,  4,  5,  8, 10,  4,  6,  6,  7,  3,  2],
       [ 3,  9,  3,  3,  2,  8,  4,  2,  7, 10,  3],
       [ 2,  9,  9,  4,  8,  4,  2,  2,  8,  3,  1],
       [ 3,  4,  5,  8,  3,  9,  6,  3,  3,  1,  5],
       [ 2,  8,  6,  5,  5,  9,  6,  1,  4,  2,  9]])

C. 각 행의 2번 인덱스를 기준으로 정렬하라.

In [4]:
indices=np.argsort(B[:,2])
C=B[indices]
C

array([[ 3,  9,  3,  3,  2,  8,  4,  2,  7, 10,  3],
       [ 2,  4,  5,  8, 10,  4,  6,  6,  7,  3,  2],
       [ 3,  4,  5,  8,  3,  9,  6,  3,  3,  1,  5],
       [ 2,  8,  6,  5,  5,  9,  6,  1,  4,  2,  9],
       [ 2,  9,  9,  4,  8,  4,  2,  2,  8,  3,  1]])

2. 아래 결과와 같이 배열을 2차원으로 입력받고, 2×2 블록 단위의 합을 새로운 배열로 생성하라.

> < 입력 >  
> [[1, 2, 3, 4],  
> [5, 6, 7, 8],   
> [9,10,11,12],   
> [13,14,15,16]]  
>
> < 출력 >   
> [[14, 22],   
> [46, 54]]   

In [5]:
input_array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
result=np.zeros((2,2),dtype=int)
for i in range(2):
    for j in range(2):
        row_start=i*2
        col_start=j*2
        block=input_array[row_start:row_start+2,col_start:col_start+2]
        result[i,j]=np.sum(block)
print(result.tolist())

[[14, 22], [46, 54]]
